version: "3"
services:
    bot-1:
      restart: "no"
      shm_size: 800m
      build:
        dockerfile: Dockerfile
        context: .
      volumes:
        - ./output:/app/output
        - ./tasks:/app/tasks
        - ./profiles:/app/profiles
      ports:
        - "3000:3000" 
        - "8000:8000" 
